[[main]]
  name = "Docs"
  url = "/docs/prologue/what-is-this"
  weight = 10

[[main]]
  name = "Data\u00A0Model"
  url= "/data-model/overview/intro"
  identifier = "data"
  weight = 30

[[main]]
  name = "Blog"
  url = "/blog/"
  weight = 40

[[docs]]
  name = "Prologue"
  weight = 10
  identifier = "prologue"
  url = "/docs/prologue/"

[[docs]]
  name = "Command line"
  weight = 20
  identifier = "chifra"
  url = "/docs/chifra/"

[[docs]]
  name = "Explorer"
  weight = 30
  identifier = "explorer"
  url = "/docs/explorer"


[[data]]
  name = "The Data Model"
  weight = 10
  identifier = "intro"
  url = "/data-model/overview/intro"

[[data]]
  name = "Trueblocks gives the data a name"
  weight = 20
  identifier = "collections"
  url = "/data-model/collections"

[[blog]]
  name = "Recipes"
  weigh = 10
  identifier = "recipes"
  url = "/blog/recipes"


[[blog]]
  name = "Explainers"
  weigh = 20
  identifier = "explainers"
  url = "/blog/explainers"


[[blog]]
  name = "Trueblocks Articles"
  weigh = 20
  identifier = "trueblocks"
  url = "/blog/trueblocks"

[[blog]]
  name = "Ethereum Articles"
  weigh = 20
  identifier = "ethereum"
  url = "/blog/ethereum"

[[social]]
  name = "Twitter"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-twitter\"><path d=\"M23 3a10.9 10.9 0 0 1-3.14 1.53 4.48 4.48 0 0 0-7.86 3v1A10.66 10.66 0 0 1 3 4s-4 9 5 13a11.64 11.64 0 0 1-7 2c9 5 20 0 20-11.5a4.5 4.5 0 0 0-.08-.83A7.72 7.72 0 0 0 23 3z\"></path></svg>"
  url = "https://twitter.com/trueblocks"
  weight = 10

[[social]]
  name = "GitHub"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-github\"><path d=\"M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22\"></path></svg>"
  url = "https://github.com/trueblocks/trueblocks-core"
  post = "v0.1.0"
  weight = 20

[[social]]
  name = "API"
  pre = "API\u00A0Reference"
  url = "https://www.tokenomics.io/api.html"
  weight = 31

[[footer]]
  name = "Privacy"
  url = "/privacy-policy/"
  weight = 30

[[footer]]
  name = "Improve these Docs"
  url = "https://github.com/TrueBlocks/trueblocks-docs"
  weight = 20
