name: Check deploy links
on:
  push:
    branches: [ master ]

jobs:
  linkinator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'

      - name: checkout deploy
        run: git checkout deploy
      
      - name: Install linkinator
        run: sudo npm install -g linkinator

      - name: check links
        run: linkinator -r docs/ papers/ index.html data-model/ api/ --skip http://localhost:23456/
